#ifndef DSL
#define DSL

#define LEFT  node->left
#define RIGHT node->right

#define OPER_NODE(a, ...)  Make_Node(OPER_CODE, {.op_code_t = a}, __VA_ARGS__)
#define NUM_NODE(num) Make_Node(NUM_CODE, {.num_t = num})
#define _C(node) Proc_Copying(node)
#define _D(node) Proc_Differing(node)

#define _ADD(node) OPER_NODE(ADD_CODE, _D(LEFT), _D(RIGHT))

#define _SUB(node) OPER_NODE(SUB_CODE, _D(LEFT), _D(RIGHT))

#define _MUL(node) OPER_NODE(ADD_CODE, OPER_NODE(MUL_CODE, _C(LEFT), _D(RIGHT)), OPER_NODE(MUL_CODE, _D(LEFT), _C(RIGHT)))

#define _DIV(node) OPER_NODE(DIV_CODE, OPER_NODE(SUB_CODE, OPER_NODE(MUL_CODE, _D(LEFT), _C(RIGHT)), OPER_NODE(MUL_CODE, _C(LEFT), _D(RIGHT))), OPER_NODE(STEPEN_CODE, _C(LEFT), NUM_NODE(2)))

#define _STEPEN(node) OPER_NODE(MUL_CODE, OPER_NODE(STEPEN_CODE, _C(LEFT), _C(RIGHT)), OPER_NODE(DIV_CODE, OPER_NODE(ADD_CODE, OPER_NODE(MUL_CODE, OPER_NODE(MUL_CODE, _C(LEFT), _D(RIGHT)), OPER_NODE(LN_CODE, _C(LEFT))), OPER_NODE(MUL_CODE, _D(LEFT), _C(RIGHT))), _C(LEFT)))

#define _SIN(node) OPER_NODE(MUL_CODE, OPER_NODE(COS_CODE, _C(LEFT)), _D(LEFT))

#define _COS(node) OPER_NODE(MUL_CODE, OPER_NODE(MUL_CODE, NUM_NODE(-1), OPER_NODE(SIN_CODE, _C(LEFT))), _D(LEFT))

#define _TAN(node) OPER_NODE(MUL_CODE, OPER_NODE(DIV_CODE, NUM_NODE(1), OPER_NODE(STEPEN_CODE, OPER_NODE(COS_CODE, _C(LEFT)), NUM_NODE(2))), _D(LEFT))

#define _COTAN(node) OPER_NODE(MUL_CODE, OPER_NODE(DIV_CODE, NUM_NODE(-1), OPER_NODE(STEPEN_CODE, OPER_NODE(SIN_CODE, _C(LEFT)), NUM_NODE(2))), _D(LEFT))

#define _ARCSIN(node) OPER_NODE(MUL_CODE, OPER_NODE(DIV_CODE, NUM_NODE(1), OPER_NODE(STEPEN_CODE, OPER_NODE(SUB_CODE, NUM_NODE(1), OPER_NODE(STEPEN_CODE, _C(LEFT), NUM_NODE(2))), NUM_NODE(0.5))), _D(LEFT))

#define _ARCCOS(node) OPER_NODE(MUL_CODE, OPER_NODE(DIV_CODE, NUM_NODE(-1), OPER_NODE(STEPEN_CODE, OPER_NODE(SUB_CODE, NUM_NODE(1), OPER_NODE(STEPEN_CODE, _C(LEFT), NUM_NODE(2))), NUM_NODE(0.5))), _D(LEFT))

#define _ARCTAN(node) OPER_NODE(MUL_CODE, OPER_NODE(DIV_CODE, NUM_NODE(1), OPER_NODE(ADD_CODE, NUM_NODE(1), OPER_NODE(STEPEN_CODE, _C(LEFT), NUM_NODE(2)))), _D(LEFT))

#define _ARCCOTAN(node) OPER_NODE(MUL_CODE, OPER_NODE(DIV_CODE, NUM_NODE(-1), OPER_NODE(ADD_CODE, NUM_NODE(1), OPER_NODE(STEPEN_CODE, _C(LEFT), NUM_NODE(2)))), _D(LEFT))

#define _LN(node) OPER_NODE(MUL_CODE, OPER_NODE(DIV_CODE, NUM_NODE(1), _C(LEFT)), _D(LEFT))

#endif